### PR TITLE
Cancel processing and animation loop

### PR DESCRIPTION
**Pull request by ogaclejapan**
I want to loop the animation : )

TextSurface has a View reference of the parent.
When the cancel processing is not, there is a possible memory leak.

### CODE REVIEW

**Comment by ogaclejapan** [comment]
Hi, @elevenetc 
Can you merge this pull request?

**Comment by elevenetc** [comment]
@ogaclejapan Hello! Sorry for delay. Nice ideas. I'm checking it now.

**Comment by elevenetc** [comment]
`cancel` doesn't work with `Parallel` animation. And this is core class which should work appropriately. It should override `cancel` of `AnimationsSet`. `AnimationsSet` works like a stack and it pops animations, so I would keep references for all animations in `Parallel` instance and call `cancel` for all of them.

**Comment by ogaclejapan** [comment]
Hi, @elevenetc 
Thank you for review.

Fixed.

**Pull request merged**
